//
//   TRD pad layout for geometry v17d
//
// automatically generated by Create_TRD_Geometry_v17d_1e.C
// created 20170501
//

#ifndef CBMTRDPADS_H
#define CBMTRDPADS_H

Int_t fst1_sect_count = 3;
// array of pad geometries in the TRD (trd1mod[1-8])
// 8 modules  // 3 sectors  // 4 values 
Float_t fst1_pad_type[8][3][4] =        
			 		 
// module type 1
// number of pads:  80 x 32 = 2560
// pad size sector 1:  0.68 cm x  1.75 cm =  1.18 cm2
// pad size sector 0:  0.68 cm x  1.50 cm =  1.01 cm2
  { { { 54.0,  6.00, 54.0/ 80,  1.50 },
      { 54.0, 42.00, 54.0/ 80,  1.75 },
      { 54.0,  6.00, 54.0/ 80,  1.50 } },

// module type 2
// number of pads:  80 x 16 = 1280
// pad size sector 1:  0.68 cm x  3.50 cm =  2.36 cm2
// pad size sector 0:  0.68 cm x  3.25 cm =  2.19 cm2
    { { 54.0, 13.00, 54.0/ 80,  3.25 },
      { 54.0, 28.00, 54.0/ 80,  3.50 },
      { 54.0, 13.00, 54.0/ 80,  3.25 } },

// module type 3
// number of pads:  80 x 16 = 1280
// pad size sector 1:  0.68 cm x  3.50 cm =  2.36 cm2
// pad size sector 0:  0.68 cm x  3.25 cm =  2.19 cm2
    { { 54.0, 13.00, 54.0/ 80,  3.25 },
      { 54.0, 28.00, 54.0/ 80,  3.50 },
      { 54.0, 13.00, 54.0/ 80,  3.25 } },

// module type 4
// number of pads:  80 x  8 =  640
// pad size sector 1:  0.68 cm x  6.75 cm =  4.56 cm2
// pad size sector 0:  0.68 cm x  6.75 cm =  4.56 cm2
    { { 54.0, 13.50, 54.0/ 80,  6.75 },
      { 54.0, 27.00, 54.0/ 80,  6.75 },
      { 54.0, 13.50, 54.0/ 80,  6.75 } },

//---

// module type 5
// number of pads: 112 x 24 = 2688
// pad size sector 1:  0.82 cm x  4.00 cm =  3.29 cm2
// pad size sector 0:  0.82 cm x  3.75 cm =  3.08 cm2
    { { 92.0, 30.00, 92.0/112,  3.75 },
      { 92.0, 32.00, 92.0/112,  4.00 },
      { 92.0, 30.00, 92.0/112,  3.75 } },

// module type 6
// number of pads: 112 x 18 = 2016
// pad size sector 1:  0.82 cm x  5.50 cm =  4.52 cm2
// pad size sector 0:  0.82 cm x  5.00 cm =  4.11 cm2
    { { 92.0, 35.00, 92.0/112,  5.00 },
      { 92.0, 22.00, 92.0/112,  5.50 },
      { 92.0, 35.00, 92.0/112,  5.00 } },

// module type 7
// number of pads: 112 x 12 = 1344
// pad size sector 1:  0.82 cm x  7.75 cm =  6.37 cm2
// pad size sector 0:  0.82 cm x  7.50 cm =  6.16 cm2
    { { 92.0, 15.00, 92.0/112,  7.50 },
      { 92.0, 62.00, 92.0/112,  7.75 },
      { 92.0, 15.00, 92.0/112,  7.50 } },

// module type 8
// number of pads: 112 x  6 =  672
// pad size sector 1:  0.82 cm x 15.50 cm = 12.73 cm2
// pad size sector 0:  0.82 cm x 15.25 cm = 12.53 cm2
    { { 92.0, 30.50, 92.0/112, 15.25 },
      { 92.0, 31.00, 92.0/112, 15.50 },
      { 92.0, 30.50, 92.0/112, 15.25 } } };

#endif
