//
//   TRD pad layout for geometry v17m
//
// automatically generated by Create_TRD_Geometry_v17m_1e.C
// created 20170601
//

#ifndef CBMTRDPADS_H
#define CBMTRDPADS_H

Int_t fst1_sect_count = 3;
// array of pad geometries in the TRD (trd1mod[1-8])
// 8 modules  // 3 sectors  // 4 values 
Float_t fst1_pad_type[8][3][4] =        
			 		 
// module type 1
// number of pads:  80 x 32 = 2560
// pad size sector 1:  0.68 cm x  1.75 cm =  1.18 cm2
// pad size sector 0:  0.68 cm x  1.50 cm =  1.01 cm2
  { { { 54.0,  6.00, 54.0/ 80,  1.50 },
      { 54.0, 42.00, 54.0/ 80,  1.75 },
      { 54.0,  6.00, 54.0/ 80,  1.50 } },

// module type 2
// number of pads:  80 x 16 = 1280
// pad size sector 1:  0.68 cm x  3.50 cm =  2.36 cm2
// pad size sector 0:  0.68 cm x  3.25 cm =  2.19 cm2
    { { 54.0, 13.00, 54.0/ 80,  3.25 },
      { 54.0, 28.00, 54.0/ 80,  3.50 },
      { 54.0, 13.00, 54.0/ 80,  3.25 } },

// module type 3
// number of pads:  80 x  8 =  640
// pad size sector 1:  0.68 cm x  6.75 cm =  4.56 cm2
// pad size sector 0:  0.68 cm x  6.75 cm =  4.56 cm2
    { { 54.0, 13.50, 54.0/ 80,  6.75 },
      { 54.0, 27.00, 54.0/ 80,  6.75 },
      { 54.0, 13.50, 54.0/ 80,  6.75 } },

// module type 4
// number of pads:  80 x  8 =  640
// pad size sector 1:  0.68 cm x  6.75 cm =  4.56 cm2
// pad size sector 0:  0.68 cm x  6.75 cm =  4.56 cm2
    { { 54.0, 13.50, 54.0/ 80,  6.75 },
      { 54.0, 27.00, 54.0/ 80,  6.75 },
      { 54.0, 13.50, 54.0/ 80,  6.75 } },

//---

// module type 5
// number of pads: 160 x 48 = 7680
// pad size sector 1:  0.68 cm x  2.25 cm =  1.52 cm2
// pad size sector 0:  0.68 cm x  2.25 cm =  1.52 cm2
    { { 108.0, 27.00, 108.0/160,  2.25 },
      { 108.0, 54.00, 108.0/160,  2.25 },
      { 108.0, 27.00, 108.0/160,  2.25 } },

// module type 6
// number of pads: 160 x 24 = 3840
// pad size sector 1:  0.68 cm x  4.50 cm =  3.04 cm2
// pad size sector 0:  0.68 cm x  4.50 cm =  3.04 cm2
    { { 108.0, 36.00, 108.0/160,  4.50 },
      { 108.0, 36.00, 108.0/160,  4.50 },
      { 108.0, 36.00, 108.0/160,  4.50 } },

// module type 7
// number of pads: 160 x 12 = 1920
// pad size sector 1:  0.68 cm x  9.00 cm =  6.08 cm2
// pad size sector 0:  0.68 cm x  9.00 cm =  6.08 cm2
    { { 108.0, 18.00, 108.0/160,  9.00 },
      { 108.0, 72.00, 108.0/160,  9.00 },
      { 108.0, 18.00, 108.0/160,  9.00 } },

// module type 8
// number of pads: 160 x  8 = 1280
// pad size sector 1:  0.68 cm x 13.50 cm =  9.11 cm2
// pad size sector 0:  0.68 cm x 13.50 cm =  9.11 cm2
    { { 108.0, 27.00, 108.0/160, 13.50 },
      { 108.0, 54.00, 108.0/160, 13.50 },
      { 108.0, 27.00, 108.0/160, 13.50 } } };

#endif
